# Generated by Django 6.0.5 on 2026-05-11 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='expected_salary',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='experience',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='skill',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='state',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
