# Generated by Django 6.0.5 on 2026-05-12 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_jobapplication_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('worker', 'Worker'), ('contractor', 'Contractor'), ('doctor', 'Doctor')], max_length=20),
        ),
    ]
