# Generated by Django 6.0.5 on 2026-05-12 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_appointment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('worker', 'Worker'), ('contractor', 'Contractor'), ('doctor', 'Doctor'), ('admin', 'Admin')], max_length=20),
        ),
    ]
